export default {
    GET_ALL_USERS_REQUESTED: 'GET_ALL_USERS_REQUESTED',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',   
    GET_USER_REQUESTED: 'GET_USER_REQUESTED',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
}